services:
  api:
    build: .
    container_name: qhse_api
    # Ports exposés uniquement pour le réseau interne Docker (Frontend -> API)
    # On ne mappe pas le port sur l'hôte pour la sécurité (accès externe bloqué)
    # ports:
    #   - "8100:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - qhse_net

  frontend:
    build: .
    container_name: qhse_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://qhse_api:8000
    depends_on:
      - api
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    command: streamlit run src/frontend/app.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - qhse_net

  scheduler:
    build: .
    container_name: qhse_scheduler
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
      - evidently
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./src:/app/src
    command: python src/scheduler.py
    networks:
      - qhse_net

  postgres:
    image: postgres:15-alpine
    container_name: qhse_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qhse_net

  prometheus:
    image: prom/prometheus:latest
    container_name: qhse_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - qhse_net

  grafana:
    image: grafana/grafana:latest
    container_name: qhse_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - qhse_net

  pushgateway:
    image: prom/pushgateway:latest
    container_name: qhse_pushgateway
    ports:
      - "9091:9091"
    networks:
      - qhse_net

  evidently:
    build:
      context: .
      dockerfile: src/data_monitoring/Dockerfile
    container_name: qhse_evidently
    ports:
      - "8101:8000"
    networks:
      - qhse_net

volumes:
  postgres_data:

networks:
  qhse_net:
    driver: bridge
