global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'qhse-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['qhse_api:8000']  # Communication interne Docker

  - job_name: 'pushgateway'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['qhse_pushgateway:9091']
